spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tE9ZJ94fnoTbEysQDZm
      secret-key: pV6kN1Cwx1gNU2dz44XeiBc28elIfm
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-zzy08

  application:
    name: gulimall-third-party

server:
  port: 30000
